import type { PaletteColor } from "./palette";

/**
 * One grid of cells; one character per cell, `.` for transparent. Frames in a
 * sprite may differ in size; they are drawn bottom-left aligned to the
 * resting frame, so a cat's paws stay on the same ground line.
 */
export type Frame = readonly string[];

/**
 * Show `frame` for `ms` milliseconds, moved by `offset` cells (`[dx, dy]`,
 * negative `dy` is up). Sprites render with visible overflow, so offsets can
 * move a sprite outside its box: runs, hops, skids.
 */
export type AnimationStep = readonly [
    frame: string,
    ms: number,
    offset?: readonly [dx: number, dy: number],
];

export interface Sprite {
    id: string;
    name: string;
    tier: "icon" | "character" | "scene";
    /** CSS pixels per cell. */
    scale: number;
    /** Maps each grid character to a palette colour. */
    key: Readonly<Record<string, PaletteColor>>;
    /**
     * Named frames. The first one is the resting frame and sets the sprite's
     * layout box. Names containing `__` are generated by `choreograph()`.
     */
    frames: Readonly<Record<string, Frame>>;
    /** Named animations. `idle` plays by default when present. */
    animations?: Readonly<Record<string, readonly AnimationStep[]>>;
}
